name: 'Create file and signing event'

on:
  push:
    paths: 
      - 'source-code/**/*.go'  # Trigger when Go files in source-code change.

jobs:
  build-go:
    name: 'Build all .go files in source-code'
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install Go
      - name: Setting up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # 3. List all files in source-code directory
      - name: List All Go Files in source-code
        run: |
          echo "Listing all Go files in source-code directory:"
          find source-code -type f -name "*.go"

      # 4. Compile all Go files
      - name: Build All Go Files
        run: |
          mkdir -p build
          echo "Building all Go files in source-code..."
          find source-code -type f -name "*.go" | while read file; do
            echo "Building $file..."
            output_name=$(basename $file .go)
            go build -o build/$output_name $file
          done

      # 5. Show results
      - name: List Build Output
        run: |
          echo "Build outputs:"
          ls -lh build/
