name: 'Create file and signing event'

on:
  push:
    paths: 
      - '*.go'  # Trigger when Go files in source-code change.

jobs:
  build-and-upload:
    name: 'Build and upload Go binaries'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      TZ: Europe/Madrid  # Set the timezone to your local timezone

    steps:
      # Step 1: Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Go
      - name: Setting up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: List all Go files in the directory
      - name: List All Go Files in the directory
        run: |
          echo "Listing all Go files in the directory:"
          find -name "*.go"

      # Step 4: Build all Go files
      - name: Build All Go Files
        run: |
          mkdir -p build
          echo "Building all Go files in the directory"
          find -name "*.go" | while read file; do
            echo "Building $file..."
            output_name=$(basename $file .go)
            go build -o build/$output_name $file
          done

      # Step 5: Show Build Results
      - name: List Build Output
        run: |
          echo "Build outputs:"
          ls -lh build/

      # Step 6: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/185640679849/locations/global/workloadIdentityPools/github/providers/github-prov
          service_account: github-actions-auth@polished-medium-445107-i9.iam.gserviceaccount.com
          access_token_lifetime: '600s'

      # Step 7: Upload binaries to Google Artifact Registry
      - name: Pushing all binaries to Google Artifact Registry
        id: pushing-GAR
        run: |
          echo "Uploading all binaries in build/ to Google Artifact Registry..."
          # Generate version with date, hour, minute, and second
            version=$(date +'%Y.%m.%d-%H.%M.%S')
          # Pass the variable to workflow outputs
            echo "::set-output name=version::$version"

          for file in build/*; do
            echo "Processing $file..."
            
            # Extract filename
            filename=$(basename "$file")

            echo "Uploading $file with version $version..."
            gcloud artifacts generic upload \
              --repository=nebula-storage \
              --location=europe-southwest1 \
              --project=polished-medium-445107-i9 \
              --package=nebula-package \
              --version="$version" \
              --source="$file"
          done

      # Step 8: Clone the target repository for index.json
      - name: Clone Target Repository for Index
        run: |
          echo "Cloning target repository for index.json..."
          git clone https://github.com/sorayaormazabalmayo/TUF_Repository_YubiKey_Vault.git tuf-repo
          cd tuf-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 9: Generate or Update index.json
      - name: Update index.json with new versions
        run: |
          cd tuf-repo
          echo "Checking for existing index.json..."
          if [ -f index.json ]; then
            echo "index.json exists, loading it."
          else
            echo "index.json does not exist, creating a new one."
            echo '{}' > index.json
          fi

          for file in ../build/*; do
            echo "Processing $file..."
            length=$(stat -c%s "$file")
            sha256=$(sha256sum "$file" | awk '{print $1}')
            filename=$(basename "$file")
            
            # Generate version with date, hour, minute, and second
            version=${{steps.pushing-GAR.outputs.version}}
            
            echo "File: $filename, Length: $length, SHA256: $sha256, Version: $version"
            
            # Add or update the entry in index.json
            jq --arg file "$filename" \
              --arg length "$length" \
              --arg sha256 "$sha256" \
              --arg version "$version" \
              '.[$file] = {length: ($length | tonumber), hashes: {sha256: $sha256}, version: $version}' index.json > tmp.json && mv tmp.json index.json
          done

          echo "Updated index.json:"
          cat index.json

      # Step 10: Commit and Push index.json to Target Repository
      - name: Commit and Push index.json
        env:
          GITHUB_TOKEN: ${{ secrets.TUF_REPO_PAT }}
        run: |
          cd tuf-repo
          echo "Checking for changes..."
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing index.json..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add index.json
            git commit -m "Update index.json with new versions"
            git push https://x-access-token:${{ secrets.TUF_REPO_PAT }}@github.com/sorayaormazabalmayo/TUF_Repository_YubiKey_Vault.git main
          else
            echo "No changes to commit."
          fi
