name: 'Create file and signing event'

# It only executes if there are changes in the /source-code repository
on:
  push:
    paths: 
      - 'source-code/**/*.go'  # Eliminar el punto extra, es incorrecto

jobs:
  build-go:
    name: 'Build changed .go files'
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install Go
      - name: Setting up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # 3. Obtain the modified files
      - name: Get Changed Go Files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'source-code/.*\.go$' || echo "")
          echo "Changed Go files: $CHANGED_FILES"
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV
      
      # 4. Compile the modified changes
      - name: Build Modified Go Files
        if: env.FILES != ''
        run: |
          mkdir -p build  # Asegura que el directorio 'build' exista
          for file in $FILES; do
            echo "Building $file..."
            output_name=$(basename $file .go)
            go build -o build/$output_name $file
          done

      # 5. Show results
      - name: List Build Output
        run: |
          echo "Build outputs:"
          ls -lh build/
