name: 'Push Target File to TUF Repository'

on:
  workflow_dispatch:  # Manually triggered for flexibility
    inputs:
      target_file:
        description: 'Path to the target file to be pushed'
        required: true
        default: 'index.json'

jobs:
  push-target-file:
    name: 'Push Target File to TUF Repository'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Compute SHA256 hash of the file and construct the branch name
      - name: Compute SHA256 and Branch Name
        id: compute-branch
        run: |
          # Compute the SHA256 hash of the target file
          sha256=$(sha256sum ${{ github.event.inputs.target_file }} | awk '{print $1}')
          echo "SHA256 hash of ${{ github.event.inputs.target_file }}: $sha256"
          
          # Construct the branch name
          branch_name="sign/$sha256"
          echo "Branch name: $branch_name"
          
          # Export the branch name for later steps
          echo "::set-output name=branch::$branch_name"
        shell: bash

      # Step 3: Clone the Remote TUF Repository
      - name: Clone TUF Repository
        env:
          TUF_REPO_URL: ${{ secrets.TUF_REPO_URL }}
        run: |
          echo "Cloning the TUF repository..."
          git clone "$TUF_REPO_URL" tuf-repo
          cd tuf-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 4: Create and Checkout the Computed Branch
      - name: Create and Checkout New Branch
        run: |
          cd tuf-repo
          git checkout -b ${{ steps.compute-branch.outputs.branch }}
          echo "Created and switched to branch ${{ steps.compute-branch.outputs.branch }}."

      # Step 5: Replace Contents of the updates-not-released-index Folder
      - name: Replace Updates-Not-Released-Index Folder Contents
        run: |
          cd tuf-repo
          echo "Deleting all contents of the updates-not-released-index folder..."
          rm -rf updates-not-released-index/*
          mkdir -p updates-not-released-index
          cp ../${{ github.event.inputs.target_file }} updates-not-released-index/index.json
          echo "Copied ${{ github.event.inputs.target_file }} to updates-not-released-index/ as index.json."

      # Step 6: Commit and Push Changes to the TUF Repository
      - name: Commit and Push Changes
        run: |
          cd tuf-repo
          git add updates-not-released-index/
          git commit -m "Replace contents of updates-not-released-index/ with index.json"
          git push origin ${{ steps.compute-branch.outputs.branch }}
